### ISSUE TITLE
Button conversion devis vers facture

### ISSUE THREAD

**Issue by Mohablogfx** [trio-SKM/ManagementStockWeb#28]
Automatiser le numéro de facture exemple (0000152).
Supprimer la zone de texte qui demande la saisie d'un numéro de facture.

Voir PJ
![image_2022-09-12_214140744](https://user-images.githubusercontent.com/84095976/189754634-ad0aa4bf-15f5-42ca-97e4-d61dea6b8e75.png)

**Comment by Mohablogfx** [comment]
Bonsoir @soufianeElkaabaoui ,
Tu peux voir stp cette partie.

**Comment by soufianeElkaabaoui** [comment]
done lhmdullah
