### ISSUE TITLE
Integrate front end with the back end

### ISSUE THREAD

**Issue by soufianeElkaabaoui** [trio-SKM/ManagementStockWeb#6]
@Mohablogfx 

- raha bayna mn l 3onwan hhhh

**Comment by Mohablogfx** [comment]
D'accord Hahiya jaya ftrii9 inchallah

**Comment by Mohablogfx** [comment]
C'est Bon pour la partie integration, Pour les pages pas encore intégrer je vais le déposer aujourd'hui.
Je vais créer des issus pour les autres pages.
